export const DATA_VERSION = 1
export const STORAGE_KEYS = Object.freeze({
  CONFIG: 'RETIREMENT_CONFIG',
  SETTINGS: 'RETIREMENT_SETTINGS',
  RECORDS: 'RETIREMENT_RECORDS',
  APP_VERSION: 'RETIREMENT_APP_VERSION',
  FIRST_VISIT: 'RETIREMENT_FIRST_VISIT',
  STORAGE_MODE: 'RETIREMENT_STORAGE_MODE',
})
